# This file is a template, and might need editing before it works on your project.
# see https://docs.gitlab.com/ce/ci/yaml/README.html for all available options

# you can delete this line if you're not using Docker
image: busybox:latest

before_script:
  - echo "Before script section"
  - git config --global user.email "4593890-MypDNS@users.noreply.gitlab.com"
  - git config --global user.name "MypDNS"
  - git remote set-url origin https://mypdns:$MypDNS_CI@gitlab.com/$CI_PROJECT_PATH.git

after_script:
  - echo -e "After script section...\n"
  - git add .
  - git status
  - git commit -m 'Auto committed from the CI runner [skip ci]'
  - git push -u origin ${CI_COMMIT_REF_NAME}

build1:
    - echo "Building"
    - git checkout -b ${CI_COMMIT_REF_NAME}
    - bash $CI_PROJECT_DIR/tld.sh

test1:
  stage: test
  script:
    - echo "Do a test here"
    - bash $CI_PROJECT_DIR/tld.sh

test2:
  stage: test
  script:
    - echo "Do another parallel test here"
    - bash $CI_PROJECT_DIR/tld.sh

deploy1:
  stage: deploy
  script:
    - echo "Do your deploy here"
    - bash $CI_PROJECT_DIR/tld.sh
