image: registry.gitlab.com/my-privacy-dns/ci-runner

variables:
  GIT_DEPTH: 2

before_script:
  - echo "Before script section"
  - git config --global user.email "4593890-MypDNS@users.noreply.gitlab.com"
  - git config --global user.name "MypDNS"
  - git remote set-url origin https://mypdns:$MypDNS_CI@gitlab.com/$CI_PROJECT_PATH.git

after_script:
  - echo -e "After script section...\n"
  - git add .
  - git status
  #- git commit -m "Last updated $(date '%A +%H:%M %Z (UTC %z)')"
  - printf "Last updated $(date '%A +%H:%M %Z (UTC %z)')\n\nWith love fromMy Privacy DNS\n<https://www.mypdns.org/source/tld/>" > $CI_PROJECT_DIR/commit_message
  - git commit -F $CI_PROJECT_DIR/commit_message
  - git push -u origin ${CI_COMMIT_REF_NAME}

build:
  stage: build
  only:
    - schedules
    - triggers
  script:
    - echo "Building"
    - git checkout -b ${CI_COMMIT_REF_NAME}
    - wget -qO- 'http://data.iana.org/TLD/tlds-alpha-by-domain.txt' | awk '/^(#|$)/{ next }; { printf("%s\n",tolower($1))}' > $CI_PROJECT_DIR/tld.list

test:
  stage: test
  except:
    - schedules
  script:
    - echo "Do a test here"
    - wget -qO- 'http://data.iana.org/TLD/tlds-alpha-by-domain.txt' | awk '/^(#|$)/{ next }; { printf("%s\n",tolower($1))}'
    - printf "Last updated $(date '%A +%H:%M %Z (UTC %z)')\n\nWith love fromMy Privacy DNS\n<https://www.mypdns.org/source/tld/>" > $CI_PROJECT_DIR/commit_message
    - cat $CI_PROJECT_DIR/commit_message
